### ISSUE TITLE
Add two Numbers

### ISSUE THREAD

**Issue by thriftykapila** [thriftykapila/Python101#5]
Do this (https://leetcode.com/problems/add-two-numbers/) question but using lists and not linked list

**Comment by dennis-pg** [comment]
Can look into this

**Comment by SowmyaaRamesh** [comment]
Hey, I would like to be assigned to this. I'm a first-timer and this seems like a good place to start. Thanks in advance.

**Comment by thriftykapila** [comment]
> Can look into this

@dennis-pg Dennis really good job bro, see if you have some cool tricks or hacks that you might share in concepts directory.

**Comment by thriftykapila** [comment]
> Can look into this

@dennis-pg @SowmyaaRamesh 

Can anyone of you look into this, its not working for the edge case of [9,9,9,9,9,9,9] and [9,9,9,9]

https://github.com/thriftykapila/Python101/blob/master/Leetcode/Medium/add2Numbers.py

**Comment by SowmyaaRamesh** [comment]
@thriftykapila I'm on it. I'll add my solution to the add2Numbers.py file as well.
